server:
  port: 9003

spring:
  application:
    name: user-service
  profiles:
    include: dev
  datasource:
    druid:
      url: jdbc:mysql://${db-mysql.host}:${db-mysql.port}/smart-recp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      username: ${db-mysql.username}
      password: ${db-mysql.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher