db-mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root



registry-center:
  host: 47.107.114.69
  port: 8848
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.114.69:8848
