server:
  port: 7001

spring:
  application:
    name: gateway-service
  profiles:
    include: dev

  redis:
    database: ${db-redis.database}
    host: ${db-redis.host}
    port: ${db-redis.port}
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: ${jwt-public-key-url}
  cloud:
    nacos:
      discovery:
        server-addr: ${registry-center.host}:${registry-center.port}
    gateway:
      routes:
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=1
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/support/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth/**,/getPublicKey
          filters:
            - StripPrefix=1
        #            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_UNIQUE
  #TODO
  #BUG
  main:
    allow-bean-definition-overriding: true