server:
  port: 9002

spring:
  application:
    name: goods-service
  profiles:
    include: dev
  redis:
    redisson:
      file: classpath:redisson.yaml
  datasource:
    druid:
      url: jdbc:mysql://${db-mysql.host}:${db-mysql.port}/smart-recp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      username: ${db-mysql.username}
      password: ${db-mysql.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: ${registry-center.host}:${registry-center.port}

seata:
  tx-service-group: smart_recp_seata_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${registry-center.host}:${registry-center.port}
      group: "SEATA_GROUP"
      namespace: ""
      username: ${registry-center.username}
      password: ${registry-center.password}
  config:
    type: nacos
    nacos:
      server-addr: ${registry-center.host}:${registry-center.port}
      group: "SEATA_GROUP"
      namespace: ""
      username: ${registry-center.username}
      password: ${registry-center.password}
  enable-auto-data-source-proxy: false

logging:
  level:
    com.smart.recp.service.goods.mapper: debug
